#!/bin/bash

# run matplotlib once to generate the font cache
python -c "import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"

test -e test.png && rm test.png

jupyter labextension install @jupyter-widgets/jupyterlab-manager@1.0 @jupyterlab/latex
jupyter lab clean && jupyter lab build